name: deoldify
channels:
- fastai
- conda-forge
- defaults
dependencies:
- pip
- fastai=1.0.60
- python=3.10
- pytorch::pytorch=1.11.0
- pytorch::torchvision
- pytorch::torchaudio
- tensorboardX
- jupyterlab
- pillow>=9.0.0
- ipywidgets
- ffmpeg
- pip:
  - ffmpeg-python
  - opencv-python>=3.3.0.10
  - wandb
  - yt-dlp
